services:
  node:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install pnpm -g && pnpm dev"
    depends_on:
      - db
    env_file:
      - .env
    labels:
      - 'traefik.http.services.sajt_node.loadbalancer.server.port=3000'
      - 'traefik.http.routers.sajt_node.rule=Host(`sajt.docker.localhost`)'

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
  node_modules:
